## QQ邮箱配置
mail:
  host: smtp.qq.com #发送邮件服务器
  username: 517309804@qq.com #发送邮件的邮箱地址
  password:  awznvjqobwkkbjfi #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
  properties.mail.smtp.port: 587
  from: 517309804@qq.com # 发送邮件的地址，和上面username一致
abc:
  config: 34566
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: 123456
