## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 517309804@qq.com #发送邮件的邮箱地址
    password:  awznvjqobwkkbjfi #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 587
    from: 517309804@qq.com # 发送邮件的地址，和上面username一致
abc:
  config: 34566

spring:
  datasource:
    name: lagou
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laogou?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false
    username: root
    password: 123456
    cloud:
      config:
        name: lagou-service-config  #配置文件名称
        profile: dev  #后缀名称
        label: master #分支名称
        uri: http://localhost:9006 
eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    metadata-map:
      cluster: cl1
      region: rn1
management:
  endpoints:
    web:
      exposure:
        include: "*"
